### ISSUE TITLE
Passing in flags from the embedder

### ISSUE THREAD

**Issue by kmiller68** [WebAssembly/conditional-sections#6]
It seems like it might be valuable to pass some flags in from the embedder. For example, to work around bugs in a particular version of some WASM implementation.

One idea would be to make flags an optional extra parameter to instantiation. e.g. `WebAssembly.instantiate(myModule, importObject, { conditionals: { needsHack, hasGC } })`. Another advantage of passing in flags is we may be able to just hand feature detection off to hosts/application authors. It's not clear how this would work with ECMAScript Module integration however... so we'd probably still need a story there.

**Comment by tlively** [comment]
Do you mean that the engine wouldn't set any conditional flags by default and the user would be responsible for determining the presence of e.g. SIMD? Or do you mean that the engine would set the flags for the features it knows it supports and the user could add more on top?

**Comment by kmiller68** [comment]
I could go either way. 

One upside of leaving it all to the user is that we don't have to worry about future naming conflicts if we leave it up to the user to determine what they need. We could also have some referencing convention that makes it impossible to confuse the default "names" and user provided ones.

**Comment by tlively** [comment]
I think the issue with leaving it up to the user is that the user is expected to use this mechanism to discover the presence of SIMD and other features, so they can't be expected to know about them ahead of time.

The JS API could prefix the user-supplied strings in some way to differentiate them from the system features. This could be a part of the API, so more than a convention. Toolchains would just have to apply the prefix to use-defined features as well.

**Comment by tlively** [comment]
Discussion in #9 has led to the conclusion that this is a good idea :+1:
