### ISSUE TITLE
Expose feature status query as a JS API

### ISSUE THREAD

**Issue by zeux** [WebAssembly/conditional-sections#7]
My understanding of the proposal as written is that it introduces an extension to wasm encoding where you can specify per-section expressions of feature sets. I would like to request that in addition to that, this proposal exposes a JS API on WebAssembly instance that allows you to query feature status - isFeatureSupported or some such.

Rationale:

1. It makes it trivial to determine if feature detection is supported from the JS side - you just query if the instance has a isFeatureSupported function (or we can add a meta-feature "feature-detection" so the check is `instance.isFeatureSupported !== undefined && instance.isFeatureSupported("feature-detection")`). This allows one to have a multi-versioned binary and provide a vanilla wasm binary as a fallback, without having to download and unsuccessfully instantiate the multi-versioned binary.

2. It makes it much easier to implement optimal download for large multi-versioned binaries. For a large wasm program, I'd expect that for some extensions their use requires duplicating of many functions - for example, if you use memcpy/memset bulk memory extensions will require multi-versioning each function that uses them and the compiler may decide to generate these calls in places without explicit memcpy/memset; ditto for SIMD. If this is the case, developer may decide to provide two separately downloaded binaries for different features - dispatching between them as it stands requires downloading or synthesizing a small "feature detection" wasm module.

You can technically implement this API yourself by synthesizing a binary WASM blob on the JS side that dynamically constructs two sections with functions that return 1 and 0, predicated on the feature. While it means that it wouldn't expose any functionality that would otherwise be impossible to implement yourself, a first-class implementation is much simpler to use, faster - you don't have to go through asynchronous wasm compilation step - and takes less code which also reduces the JS size impact of the feature detection code. My understanding is that the browser implementation will also be simple.

**Comment by tlively** [comment]
I'm not opposed to a native JS API for feature detection, but JS APIs are not my area of expertise. Given how simple it is to do feature detection with small libraries, I don't know if there will an appetite among the JS people for adding this API. Perhaps @ajklein can comment on that or point us to the right people to ask.

> This allows one to have a multi-versioned binary and provide a vanilla wasm binary as a fallback, without having to download and unsuccessfully instantiate the multi-versioned binary.

Even without a native JS API, I would not expect anyone to fall back to MVP after downloading and attempting to instantiate a large binary. Tiny feature-detection libraries like https://github.com/GoogleChromeLabs/wasm-feature-detect or https://github.com/MaxGraey/wasm-check would be better for detecting whether multiversioning is supported at all. Making this proposal MVP-compatible is also not off the table, and will in fact be discussed at the CG meeting tomorrow. See #5. 

> For a large wasm program, I'd expect that for some extensions their use requires duplicating of many functions...

I agree that in cases with a lot of duplication, it is much better to serve different binaries for different feature sets. For bulk memory operations and SIMD, I would hope that only a few functions would need to be replaced. For bulk memory in particular, only memcpy, memset, and friends would need to be replaced.

**Comment by zeux** [comment]
> For bulk memory operations and SIMD, I would hope that only a few functions would need to be replaced. For bulk memory in particular, only memcpy, memset, and friends would need to be replaced.

It depends on the compiler heuristics I suppose; my expectation is that any calls to memcpy/memset are going to be replaced with inlined bulk memory operations, and additionally large struct copies may start using this as well. For SIMD similarly there may be cases where, say, struct copies are done using SIMD registers if SIMD is available - at least that's definitely how clang optimizes for x64 et al.

**Comment by tlively** [comment]
@zeux With function multiversioning, LLVM would only use bulk memory or SIMD operations in the specific functions where those particular target features were available and would stick to the baseline feature set for all other functions. So only explicitly multiversioned functions would ever have to be duplicated. Emscripten would probably want to provide multiversioned memcpy etc. but for SIMD I expect almost all multiversioned functions would be in user code.

On a separate note, #9 actually proposes removing feature detection entirely from this proposal and only keeping conditional compilation. That would not preclude having a JS feature detection API, but it would make that a separate question.

**Comment by ajklein** [comment]
My understanding from other proposals is that JS API additions would be part of the same proposal, by making additions to the js-api portion of the spec in this repo. At first glance exposing something in JS for this seems plausible to me, @Ms2ger and @littledan might have opinions as well.

**Comment by littledan** [comment]
[Caveat: I don't have much background on this area, and I'm speaking mostly about my general impressions.]

I don't think it should be a big problem to add a JS API extension in the same proposal, from a specification, implementation or testing perspective, and I generally like idea of doing so. In addition to permitting more lazy fetching without the need to ship a polyfill of this API, it seems like a JS API could allow for more incremental, flexible adoption by toolchains (where everyone has a bunch of JS logic anyway).
