### ISSUE TITLE
Proposal name change

### ISSUE THREAD

**Issue by tlively** [WebAssembly/conditional-sections#8]
In the meeting today, the CG consented to changing the name of this proposal to something that more accurately describes what the proposal is all about. We can discuss the name here and once we have consensus we can change the name of the repo without having to go back to the CG for permission.

Although "feature detection" is the primary motivation behind this proposal, it does not accurately describe the mechanism we have currently designed. I was thinking "conditional compilation" would be better, but it was correctly pointed out in the CG meeting that the conditional sections influence decoding more than compilation.

@rossberg suggested "conditional sections" and I think that is an excellent name given our current design. Barring large changes due to #5, I propose we adopt the "conditional sections" name. Are there any other ideas out there?

**Comment by tlively** [comment]
I think it would be good to change the name to "conditional sections" now. @binji Do you have permissions to do that name change?

**Comment by binji** [comment]
Yep, I can do it. Considering no one else suggested another name, let's go with `conditional-sections`

**Comment by binji** [comment]
Done! We'll probably want to update various documents here and elsewhere too (I've already updated github.com/WebAssemly/proposals)
